name: macOS Remote Access Setup

on:
  workflow_dispatch:

jobs:
  setup-remote-access:
    runs-on: macos-latest
    steps:
    - name: Enable Screen Sharing
      run: |
        # Enable Screen Sharing (VNC)
        sudo /usr/sbin/systemsetup -setremotelogin on
        sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.screensharing -dict Disabled -bool false
        sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
        
        # Create a temporary user for remote access
        TEMP_USER="githubrunner"
        TEMP_PASS=$(openssl rand -base64 12)
        sudo sysadminctl -addUser $TEMP_USER -password $TEMP_PASS -admin
        
        # Get IP address
        IP_ADDRESS=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
        
        echo "Remote access enabled on: $IP_ADDRESS"
        echo "Username: $TEMP_USER"
        echo "Password: $TEMP_PASS"
        echo ""
        echo "To connect from macOS:"
        echo "1. Open Finder"
        echo "2. Press Command+K"
        echo "3. Enter: vnc://$IP_ADDRESS"
        echo "4. Use the credentials above"
        echo ""
        echo "To connect from Windows:"
        echo "1. Download TigerVNC Viewer from https://tigervnc.org"
        echo "2. Connect to $IP_ADDRESS"
        echo "3. Use the credentials above"
        
        # Keep alive for 30 minutes
        sleep 1800
