- name: Download and Install RustDesk
      run: |
        # Download the latest RustDesk macOS client (adjust URL if needed for a specific version)
        # It's good practice to make the version dynamic or match the download to the expected mount name
        RUSTDESK_VERSION="1.2.3" # Define the version here
        RUSTDESK_ARCH="aarch64" # Or x86_64 for Intel Macs
        DMG_FILENAME="rustdesk-${RUSTDESK_VERSION}-${RUSTDESK_ARCH}.dmg"
        MOUNT_POINT="/Volumes/rustdesk-${RUSTDESK_VERSION}" # This is the crucial change

        curl -L "https://github.com/rustdesk/rustdesk/releases/download/${RUSTDESK_VERSION}/${DMG_FILENAME}" -o "${DMG_FILENAME}"

        sudo hdiutil attach "${DMG_FILENAME}"
        # Use the correct mount point for copying
        sudo cp -R "${MOUNT_POINT}/RustDesk.app" /Applications/
        sudo hdiutil detach "${MOUNT_POINT}"

        # Give RustDesk necessary permissions (might require manual approval on first run)
        # These commands attempt to pre-approve, but user interaction might still be needed
        sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT or REPLACE INTO access (service, client, client_type, allowed, prompt_count, csreq, policy_id, indirect_object_identifier, indirect_object_identifier_type, indirect_object_code_identity) VALUES ('kTCCServiceScreenCapture', 'com.rustdesk.rustdesk', 0, 1, 0, NULL, 0, 'kTCCServiceScreenCapture', 0, NULL);"
        sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT or REPLACE INTO access (service, client, client_type, allowed, prompt_count, csreq, policy_id, indirect_object_identifier, indirect_object_identifier_type, indirect_object_code_identity) VALUES ('kTCCServiceAccessibility', 'com.rustdesk.rustdesk', 0, 1, 0, NULL, 0, 'kTCCServiceAccessibility', 0, NULL);"
